name: Build Windows Executable

on:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Build
        run: |
          pyinstaller main.py --onefile --add-data "resources;resources" --hidden-import=sqlalchemy --hidden-import=fpdf
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/*
